site_name: Res4557RTD
nav:
  - Home: index.md
  - About: about.md
  - Resolução Markdown: res.md
  - BCP: glossary/bcp.md
  - ECL: glossary/ecl.md
  - ERM: glossary/ermp.md
  - IRRBB: glossary/irrbb.md
  - RAS: glossary/ras.md
  - TPRM: glossary/tprm.md
plugins:
  - search
theme: readthedocs
markdown-extensions:
  - attr_list